version: 1
extends: _base
workflow:
  image: rg.nl-ams.scw.cloud/reactis/opencode:1.3
  imagePullSecrets:
    - name: registry
  workingDir: "[%WORKDIR%]"
  timeoutSeconds: 14400
  ttlSecondsAfterFinished: 300
  envFiles:
    - /root/.config/agentis/agentis.env
  env:
    AGENT_BROWSER_SCREENSHOT_DIR: "[%RUN_DIR%]/.screenshots"
    IS_SANDBOX: 1
  steps:
    - name: Run agent
      uses: run-agent