version: 1
extends: _base
workflow:
  env:
    TASK_NUMBER: "[%TASK_NUMBER%]"
    TASK_TITLE: "[%TASK_TITLE%]"
    AGENT_BROWSER_SCREENSHOT_DIR: "[%RUN_DIR%]/.screenshots"
    IS_SANDBOX: 1
    CLARP_DEBUG_PTY: 1
    CLARP_DEBUG: 1
    CLARP_DEBUG_API: 1
    PYTHONPATH: "[%WORKDIR%]/backend"
    PATH: "[%WORKDIR%]/.venv/bin:/root/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  volumeMounts:
    - name: npm-cache
      mountPath: /root/.npm
    - name: poetry-cache
      mountPath: /root/.cache/pypoetry
    - name: claudecodejson
      mountPath: /root/.claude.json
    - name: claudecode
      mountPath: /root/.claude
  steps:
    - name: Run agent
      uses: run-agent
volumes:
  - name: npm-cache
    hostPath:
      path: /root/.npm
      type: DirectoryOrCreate
  - name: poetry-cache
    hostPath:
      path: /root/.cache/pypoetry
      type: DirectoryOrCreate
  - name: claudecode
    hostPath:
      path: /root/.claude
      type: DirectoryOrCreate
  - name: claudecodejson
    hostPath:
      path: /root/.claude.json
