apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner-[%NAMESPACE%]
  namespace: default
spec:
  selector:
    matchLabels:
      app: runner-[%NAMESPACE%]
  template:
    metadata:
      labels:
        app: runner-[%NAMESPACE%]
    spec:
      containers:
        - name: runner
          workingDir: "[%WORKDIR%]"
          securityContext:
            allowPrivilegeEscalation: true

      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: runner-[%NAMESPACE%]
spec:
  selector:
    app: runner-[%NAMESPACE%]
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4096
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner-[%NAMESPACE%]
spec:
  rules:
    - host: "[%NAMESPACE%].dev.agentis.cz"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: runner
                port:
                  number: 80
